.Dd $Mdocdate: July 10 2015 $
.Dt YANK 1
.Os
.Sh NAME
.Nm yank
.Nd yank terminal output to clipboard
.Sh SYNOPSIS
.Nm yank
.Op Fl lx | v
.Op Fl d Ar delim
.Op Fl - Ar command Op Ar argument ...
.Sh DESCRIPTION
Read input from
.Pa stdin
and display a selection interface that allows a field to be selected and copied
to the clipboard. Fields are determined by splitting the input on a delimiter
sequence, optionally specified using the
.Fl d
option, see
.Em DELIMITERS .
.Pp
Using the arrow keys will move the selected field. The interface support several
Emacs like key bindings, see
.Em COMMANDS .
Pressing the return key will invoke the yank command and write the selected
field to the its
.Pa stdin .
The yank command defaults to
.Xr xsel 1
but could be anything that accepts input on
.Pa stdin .
When invoking yank everything supplied after the
.Fl -
option will be used as the yank command, see
.Em EXAMPLES .
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl d Ar delim
use all characters in
.Ar delim
as field delimiters
.It Fl l
use the default delimiters except for space, see
.Em DELIMITERS
.It Fl v
prints version
.It Fl x
use alternate screen
.It Fl - Ar command Op Ar argument ...
use
.Ar command
with zero or more
.Ar argument
as the yank command
.El
.Sh COMMANDS
.Bl -tag -width -indent
.It Ctrl-A
move selection to the first field
.It Ctrl-C
exit without invoking the yank command
.It Ctrl-E
move selection to the last field
.It Ctrl-N or Right
move selection to the right
.It Ctrl-P or Left
move selection to the left
.It Down
move selection to the next line
.It Up
move selection to the previous line
.It Enter
exit using the selected field
.El
.Sh DELIMITERS
The following characters are always recognized as delimiters:
.Bl -tag -width -indent
.It \en
new line
.It \er
carriage return
.It \et
horizontal tab
.El
If the
.Fl d
and
.Fl l
options are omitted space is also recognized as a delimiter.
.Sh EXAMPLES
Yank a environment variable key or value:
.Pp
.Dl env | yank -d =
.Pp
Yank a field from a CSV file:
.Pp
.Dl yank -d \e\&", <file.csv
.Pp
Yank a whole line using the
.Fl l
option:
.Pp
.Dl make 2>&1 | yank -l
.Pp
If
.Pa stdout
is not a terminal the selected field will be written to
.Pa stdout
and exit without invoking the yank command. Kill the selected PID:
.Pp
.Dl ps ux | yank | xargs kill
.Pp
Yank the selected field to the clipboard as opposed of the default primary
clipboard:
.Pp
.Dl yank -- xsel -b
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An "Anton Lindqvist" Aq anton.lindqvist@gmail.com
